import type { Metadata } from "next";
import { Geist, Geist_Mono, Press_Start_2P } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pressStart2 = Press_Start_2P({
  variable: "--font-press-start-2p",
  subsets: ["latin"],
  weight : '400'
})

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  }
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<
  RootLayoutProps
>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pressStart2.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
